version: "3.8"

services:
  backend:
    build: .
    container_name: bms-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    restart: always

  frontend:
    build:
      context: ../BMS-frontend  # adjust path if needed
    container_name: bms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
